### ISSUE TITLE
Add css theme for html output rendering

### ISSUE THREAD

**Issue by kbroch-rivosinc** [riscv/docs-resources#3]
This relates to https://github.com/riscv/docs-spec-template/issues/18

I can provide a PR that will attempt to get rendered html closer to style in pdf unless there is something else already in the works.

**Comment by wmat** [comment]
Hi Kevin, circling back on this one, I don't think we need CSS.  The current PDF theme will get deprecated when we move to [asciidoctor-web-pdf](https://github.com/ggrossetie/asciidoctor-web-pdf) in the document toolchain.  This tool replaces the asciidoctor-pdf tool which has basically become abandoned.  Asciidoctor-web-pdf relies on the web browsers PDF generation from the HTML.  I'm going to close this, however if you feel we still need it, feel free to re-open.
